$scope.weaponType = [
    {name:"Ammunition",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"BattleAxe",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Blow Gun",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Club",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Dagger",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Dart",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Flail",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Glaive",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Great Axe",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Great Club",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Great Sword",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Halberd",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Hand Axe",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Hand Crossbow",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Heavy Crossbow",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Javelin",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Lance",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Light Crossbow",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Light Hammer",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Longbow",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Longsword",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Mace",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Maul",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Morningstar",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Net",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Pike",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Quarterstaff",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Rapier",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Scimitar",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Shortbow",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Shortsword",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Sickle",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Sling",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Spear",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Trident",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"War Pick",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Warhammer",
     damage: "",
     Properties:"",
     cost: "",
     weight: "",
     },
    {name:"Whip",
     damage: "",
     Properties:"",
     cost: "",
     weight: ""},
];
